// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace DemoSec.SitePages {
	
	
	public partial class myfeed {
		
		protected System.Web.UI.WebControls.Content Content1;
		
		protected System.Web.UI.WebControls.Content Content2;
		
		protected System.Web.UI.WebControls.LinkButton btn_edit;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl block1;
		
		protected System.Web.UI.HtmlControls.HtmlGenericControl block2;
	}
}
